name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the Docker image
        run: |
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          docker build \
            --build-arg SHORT_SHA=$SHORT_SHA \
            --build-arg GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
            --build-arg GITHUB_ACTOR=${{ github.actor }} \
            -t ghcr.io/${{ github.repository }}/java-base-service:latest .
          docker build \
            --build-arg SHORT_SHA=$SHORT_SHA \
            --build-arg GITHUB_TOKEN=${{ secrets.GITHUB_TOKEN }} \
            --build-arg GITHUB_ACTOR=${{ github.actor }} \
            -t ghcr.io/${{ github.repository }}/java-base-service:${SHORT_SHA} .

      - name: Push the Docker image
        run: |
          SHORT_SHA=$(echo "${{ github.sha }}" | cut -c1-7)
          docker push ghcr.io/${{ github.repository }}/java-base-service:latest
          docker push ghcr.io/${{ github.repository }}/java-base-service:${SHORT_SHA}
